import { NextResponse } from "next/server";

export async function POST() {
  const data = {
    eventType: "intense_sunlight",
    timestamp: "2025-08-14T10:39:50.5036326",
    totalDemand: 400.8,
    totalAllocatedCapacity: 400.8,
    sourceAllocations: [
      {
        sourceId: "source_panel",
        sourceType: "Solar Panel",
        allocatedCapacity: 400.8,
        utilizationPercent: 97.6,
        cost: 8.016,
        priority: "primary",
        justification:
          "Utilized solar energy due to its low operational cost and high efficiency under current conditions.",
        startupTimeMinutes: 0,
        operationalNotes: ["High utilization - monitor performance closely"],
        previousUsage: 380.0,
        newUsage: 780.8,
        previousCapacity: 450.0,
        newCurrentCapacity: 49.2,
        maxCapacity: 800.0,
        status: "online",
        operationalCost: 0.02,
        efficiency: 88.5,
        constraints: [
          "daylight_only",
          "thermal_derating_above_module_temp_45C",
          "inverter_dc_clipping_above_95%_dc_capacity",
          "ramp_rate_limit_10%_per_min",
        ],
        alerts: [
          "intense_sunlight_detected",
          "high_uv_index_12",
          "panel_temperature_monitoring_active",
          "mppt_optimization_recommended",
        ],
        impactAnalysis: {},
      },
      {
        sourceId: "source_grid",
        sourceType: "Grid",
        allocatedCapacity: 0.0,
        utilizationPercent: 63.33,
        cost: 0.0,
        priority: "unused",
        justification:
          "Grid power remains as a backup to ensure demand is fully met.",
        startupTimeMinutes: 5,
        operationalNotes: [],
        previousUsage: 950.0,
        newUsage: 950.0,
        previousCapacity: 1200.0,
        newCurrentCapacity: 1200.0,
        maxCapacity: 1500.0,
        status: "online",
        operationalCost: 0.08,
        efficiency: 95.0,
        constraints: [
          "peak_hour_pricing",
          "import_cap_ceil_based_on_contract",
          "min_grid_spin_as_reliability_buffer_5%",
        ],
        alerts: ["grid_connection_stable"],
        impactAnalysis: {},
      },
      {
        sourceId: "source_diesel_generator",
        sourceType: "Diesel Generator",
        allocatedCapacity: 0.0,
        utilizationPercent: 0.0,
        cost: 0.0,
        priority: "unused",
        justification: "Diesel generator kept on standby for emergencies.",
        startupTimeMinutes: 120,
        operationalNotes: [],
        previousUsage: 0.0,
        newUsage: 0.0,
        previousCapacity: 0.0,
        newCurrentCapacity: 0.0,
        maxCapacity: 600.0,
        status: "ses",
        operationalCost: 0.15,
        efficiency: 82.0,
        constraints: [
          "fuel_dependent",
          "emission_limits",
          "use_prohibited_during_solar_surplus_except_emergency",
        ],
        alerts: ["fuel_level_at_85%", "kept_on_cold_standby"],
        impactAnalysis: {},
      },
      {
        sourceId: "source_battery_storage",
        sourceType: "Battery Storage",
        allocatedCapacity: 0.0,
        utilizationPercent: 12.5,
        cost: 0.0,
        priority: "unused",
        justification:
          "Battery storage is available but not utilized due to sufficient solar capacity.",
        startupTimeMinutes: 1,
        operationalNotes: [],
        previousUsage: 50.0,
        newUsage: 50.0,
        previousCapacity: 300.0,
        newCurrentCapacity: 300.0,
        maxCapacity: 400.0,
        status: "online",
        operationalCost: 0.05,
        efficiency: 93.0,
        constraints: [
          "charge_dependent",
          "limited_duration",
          "min_reserve_soc_20%",
          "max_charge_rate_c0.5",
          "prefer_charge_when_solar_surplus",
        ],
        alerts: [
          "battery_charge_window_open",
          "state_of_charge_75%",
          "curtailment_if_soc_≥_95%_and_low_load",
        ],
        impactAnalysis: {},
      },
    ],
    optimizationStrategy: "cost_efficiency_with_reliability",
    rationale:
      "Solar energy is prioritized due to low operational cost and high efficiency. Battery storage is utilized for reliability and to manage fluctuations in demand. Grid power is included as a backup to ensure demand is fully met.",
    confidence: 90,
    totalCost: 8.016,
    efficiency: 88.5,
    recommendations: [
      "Monitor solar panel performance closely due to high UV index.",
      "Ensure battery storage is charged to optimal levels before potential cloud cover increases.",
      "Prepare for potential energy demand spikes by adjusting HVAC settings.",
    ],
    performanceMetrics: {},
    contingencyPlan:
      "Activate diesel generator if demand exceeds available capacity from selected sources.",
    demandPredictorReasoning: {
      agentName: "DemandPredictorAgent",
      analysis:
        "The current weather conditions indicate a temperature of 20.8°C with 70.8% humidity and a cloud cover of 24.4%. The solar irradiance is high at 665.5 W/m², which is favorable for solar energy production. However, the forecast indicates a slight increase in cloud coverage by 16% and a minor decrease in irradiance by 1%. Given these conditions, the facility's energy demand is expected to remain stable at around 400.8 kW, as the intense sunlight event will likely enhance operational efficiency and reduce reliance on grid power.",
      keyFactors: [
        "Current solar irradiance levels",
        "Increased cloud coverage forecast",
        "Historical consumption patterns during similar weather events",
      ],
      recommendations: [
        "Monitor solar panel performance closely due to high UV index.",
        "Ensure battery storage is charged to optimal levels before potential cloud cover increases.",
        "Prepare for potential energy demand spikes by adjusting HVAC settings.",
      ],
      confidence: 90,
      supportingData: {
        currentWeather: {
          temperature: 20.8,
          humidity: 70.8,
          cloudCover: 24.4,
          solarIrradiance: 665.5,
          windSpeed: 7.6,
          description: "Cloudy",
        },
        weatherChangeForecast: {
          cloudCoverageChange: "+16%",
          irradianceChange: "-1%",
          forecastAccuracy: 90.0,
        },
        historicalConsumption: {
          consumption: 400.8,
          confidence: 90.0,
        },
      },
      strategy: null,
      rationale: null,
    },
    sourceSelectorReasoning: {
      agentName: "SourceSelectorAgent",
      analysis: null,
      keyFactors: null,
      recommendations: [
        "Monitor solar panel performance closely due to high UV index.",
        "Ensure battery storage is charged to optimal levels before potential cloud cover increases.",
        "Prepare for potential energy demand spikes by adjusting HVAC settings.",
      ],
      confidence: 90,
      supportingData: {
        backupSources: [
          {
            sourceType: "diesel_generator",
            reason:
              "Available as a backup if solar and battery storage are insufficient.",
          },
        ],
        emergencyActions: [
          "Activate diesel generator if demand exceeds available capacity from selected sources.",
        ],
      },
      strategy: "cost_efficiency_with_reliability",
      rationale: [
        "Solar energy is prioritized due to low operational cost and high efficiency.",
        "Battery storage is utilized for reliability and to manage fluctuations in demand.",
        "Grid power is included as a backup to ensure demand is fully met.",
      ],
    },
    energyDistributorReasoning: {
      agentName: "EnergyDistributorAgent",
      analysis:
        "Solar energy is prioritized due to low operational cost and high efficiency. Battery storage is utilized for reliability and to manage fluctuations in demand. Grid power is included as a backup to ensure demand is fully met.",
      keyFactors: null,
      recommendations: [
        "Monitor solar panel performance closely due to high UV index.",
        "Ensure battery storage is charged to optimal levels before potential cloud cover increases.",
        "Prepare for potential energy demand spikes by adjusting HVAC settings.",
      ],
      confidence: 90,
      supportingData: {},
      strategy: "cost_efficiency_with_reliability",
      rationale: null,
    },
  };

  return NextResponse.json(data);
}
