spring:
  application:
    name: cps-system

### OpenAPI / Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

### LangChain4J Configuration for OpenAI Chat Model
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
      temperature: 0.3